
default: &default
  adapter: postgresql
  host: localhost
  database: battleship
  username: battleship
  password: battleship

development:
  <<: *default

test:
  <<: *default
  database: battleship-test

production:
  <<: *default
  database: battleship-production
