# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c78121740c0733fbc076dc33b3a366f1bb6a6708e75fa5b830547038fe5dfd588e0a3c5bef62502970fe1fd6ca97eb2c5cb884b11aab9db0fdfb07037e8ef6b

test:
  secret_key_base: 770840d128c6cce9b96aca46fbfa0fa859f7958de0d16196c1e350ccbb21cdfbf525aecad58dd23eaee110ad15228ad352a1f5a777e9520b64b5f3b3fd2b882e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
